### ISSUE TITLE
slammers get all wimpy when there toes are wet

### ISSUE THREAD

**Issue by JamesPagetButler** [aldrik/pa-mods#4]
slammers can't shoot if they are partially submerged

**Comment by aldrik** [comment]
Although there is a `DeepWater` layer in engine, surface units only transfer between `Underwater` and `LandHorizontal`, there's no _ShallowWater_ layer. It doesn't make sense for bullet projectiles to be usable underwater. Indeed _some_ of the commanders have this and yes that needs a cosmetic fix.
